User.destroy_all
Clinic.destroy_all
Doctor.destroy_all

aarp = Insurance.create(name: "AARP")
aetna = Insurance.create(name: "Aetna")
allstate = Insurance.create(name: "Allstate")
ambetter = Insurance.create(name: "Ambetter")
american_Family_Insurance = Insurance.create(name: "American Family Insurance")
american_national_Insurance = Insurance.create(name: "American National Insurance Company")
amerigroup = Insurance.create(name: "Amerigroup")
anthem = Insurance.create(name: "Anthem")
bcbs = Insurance.create(name: "Blue Cross and Blue Shield Association")
careSource = Insurance.create(name: "CareSource")
cambia = Insurance.create(name: "Cambia Health Solutions")
centene = Insurance.create(name: "Centene Corporation")
cigna = Insurance.create(name: "Cigna")
coventry_Health_Care = Insurance.create(name: "Coventry Health Care")
delta_Dental = Insurance.create(name: "Delta Dental")
emblemHealth = Insurance.create(name: "EmblemHealth")
fortis = Insurance.create(name: "Fortis")
geisinger = Insurance.create(name: "Geisinger")
golden_rule = Insurance.create(name: "Golden Rule Insurance Company")
group_Health_Cooperative = Insurance.create(name: "Group Health Cooperative")
group_Health_Incorporated = Insurance.create(name: "Group Health Incorporated")
harvard_Pilgrim_Health_Care = Insurance.create(name: "Harvard Pilgrim Health Care")
health_Net = Insurance.create(name: "Health Net")
healthMarkets = Insurance.create(name: "HealthMarkets")
healthPartners = Insurance.create(name: "HealthPartners")
healthSpring = Insurance.create(name: "HealthSpring")
highmark = Insurance.create(name: "Highmark")
horace_Mann_Educators_Corporation = Insurance.create(name: "Horace Mann Educators Corporation")
humana = Insurance.create(name: "Humana")
independence_Blue_Cross = Insurance.create(name: "Independence Blue Cross")
kaiser_Permanente = Insurance.create(name: "Kaiser Permanente")
kaleida_Health = Insurance.create(name: "Kaleida Health")
liberty_Medical = Insurance.create(name: "Liberty Medical")
liberty_mutual = Insurance.create(name: "Liberty Mutual")
lifeWise_Health_Plan = Insurance.create(name: "LifeWise Health Plan of Oregon")
massHealth = Insurance.create(name: "MassHealth")
medica = Insurance.create(name: "Medica")
medicare = Insurance.create(name: "Medicare")
medical_Mutual = Insurance.create(name: "Medical Mutual of Ohio")
mega_Life_and_Health_Insurance = Insurance.create(name: "MEGA Life and Health Insurance")
molina_Healthcare = Insurance.create(name: "Molina Healthcare")
oscar_Health = Insurance.create(name: "Oscar Health")
oxford_Health_Plans = Insurance.create(name: "Oxford Health Plans")
premera_Blue_Cross = Insurance.create(name: "Premera Blue Cross")
principal_Financial_Group = Insurance.create(name: "Principal Financial Group")
shelter_Insurance = Insurance.create(name: "Shelter Insurance")
state_Farm = Insurance.create(name: "State Farm")
the_hartford = Insurance.create(name: "The Hartford")
thrivent_Financial = Insurance.create(name: "Thrivent Financial for Lutherans")
unitedHealth_Group = Insurance.create(name: "UnitedHealth Group")
unitrin = Insurance.create(name: "Unitrin")
universal_American_Corporation = Insurance.create(name: "Universal American Corporation")
us_Health_Group = Insurance.create(name: "US Health Group")
vantage_Health_Plan = Insurance.create(name: "Vantage Health Plan")
wellCare = Insurance.create(name: "WellCare")
#----------------------------------------------------------SPECIALTIES------------------------------------------------------------------------------------------------------------------------------------------------#

allergy = Specialty.create(name: "Allergy and immunology")
anesthesiology = Specialty.create(name: "Anesthesiology")
cardiology = Specialty.create(name: "Cardiology")
cardiovascular = Specialty.create(name: "Cardiovascular surgery")
clinical = Specialty.create(name: "Clinical laboratory sciences")
dermatology = Specialty.create(name: "Dermatology")
dietetics = Specialty.create(name: "Dietetics")
emergency_medicine = Specialty.create(name: "Emergency medicine")
endocrinology = Specialty.create(name: "Endocrinology")
family_medicine = Specialty.create(name: "Family medicine")
forensic_medicine = Specialty.create(name: "Forensic medicine")
gastroenterology = Specialty.create(name: "Gastroenterology")
general_surgery = Specialty.create(name: "General surgery")
geriatrics = Specialty.create(name: "Geriatrics")
gynecology = Specialty.create(name: "Gynecology")
hepatology = Specialty.create(name: "Hepatology")
hospital_medicine = Specialty.create(name: "Hospital medicine")
infectious_disease = Specialty.create(name: "Infectious disease")
intensive_care_medicine = Specialty.create(name: "Intensive care medicine")
internal_medicine = Specialty.create(name: "Internal Medicine")
medical_research = Specialty.create(name: "Medical research")
nephrology = Specialty.create(name: "Nephrology")
obstetrics_and_gynecology = Specialty.create(name: "Obstetrics and gynecology")
oncology = Specialty.create(name: "Oncology")
oral_and_maxillofacial_surgery = Specialty.create(name: "Oral and maxillofacial surgery")
orthopedic_surgery = Specialty.create(name: "Orthopedic surgery")
otorhinolaryngologyent_ent = Specialty.create(name: "Otorhinolaryngology/ENT")
palliative_care = Specialty.create(name: "Palliative care")
pathology = Specialty.create(name: "Pathology")
pediatrics = Specialty.create(name: "Pediatrics")
pediatric_surgery = Specialty.create(name: "Pediatric surgery")
physiatry = Specialty.create(name: "Physical medicine and rehabilitation")
plastic_surgery = Specialty.create(name: "Plastic surgery")
podiatry = Specialty.create(name: "Podiatry")
proctology = Specialty.create(name: "Proctology")
psychiatry = Specialty.create(name: "Psychiatry")
pulmonology = Specialty.create(name: "Pulmonology")
public_health = Specialty.create(name: "Public Health")
radiology = Specialty.create(name: "Radiology")
rheumatology = Specialty.create(name: "Rheumatology")
surgical_oncology = Specialty.create(name: "Surgical oncology")
thoracic_surgery = Specialty.create(name: "Thoracic surgery")
transplant_surgery = Specialty.create(name: "Transplant surgery")
urgent_Care_Medicine = Specialty.create(name: "Urgent Care")
urology = Specialty.create(name: "Urology")
vascular_surgery = Specialty.create(name: "Vascular surgery")

chicagoHospital = Clinic.create(name:"Mitchell Hospital - Hyde Park", email: 'islam@gmail.com', address: "5815 S Maryland Ave" , state:"IL" , city: "Chicago" , zip: 60637, rating: 4, password: "111111")                                           
chicagoHospital2 = Clinic.create(name:"Comer Children's Hospital", email: 'islam@gmail.com', address: "5721 S Maryland Ave" , state:"IL" , city: "Chicago" , zip: 60637, rating: 4, password: "111111")
chicagoHospital3 = Clinic.create(name:"The University of Chicago Medicine", email: 'islam@gmail.com', address: "5841 S Maryland Ave" , state:"IL" , city: "Chicago" , zip: 60637, rating: 4, password: "111111")
chicagoHospital4 = Clinic.create(name:"Advocate Good Samaritan Hospital", email: 'islam@gmail.com', address: "3815 Highland Ave" , state:"IL" , city: "Downers Grove" , zip: 60515, rating: 4, password: "111111")
chicagoHospital5 = Clinic.create(name:"Northwestern Medicine Central DuPage Hospital", email: 'islam@gmail.com', address:"25 North Winfield Rd" , state:"IL" , city: "Winfield" , zip: 60190, rating: 4, password: "111111")
chicagoHospital6 = Clinic.create(name:"Marianjoy Rehabilitation Hospital", email: 'islam@gmail.com', address:"26W171 W Roosevelt Rd" , state:"IL" , city: "Wheaton" , zip: 60187, rating: 4, password: "111111")
chicagoHospital7 = Clinic.create(name:"Elmhurst Hospital - Main Campus", email: 'islam@gmail.com', address:"155 E Brush Hill Rd" , state:"IL" , city: "Elmhurst" , zip: 60126, rating: 4, password: "111111")
chicagoHospital8 = Clinic.create(name:"Adventist GlenOaks Hospital", email: 'islam@gmail.com', address:"25 North Winfield Rd" , state:"IL" , city: "Winfield" , zip: 60190, rating: 4, password: "111111")
chicagoHospital9 = Clinic.create(name:"Northwestern Medicine Immediate Care Bloomingdale", email: 'islam@gmail.com' , address:"235 S Gary Ave" , state:"IL" , city: "Bloomingdale" , zip: 60198, rating: 4, password: "111111")
chicagoHospital10 = Clinic.create(name:"Amital Health Adventist Medical Center Hinsdale", email: 'islamm@gmail.com', address:"120 N Oak St" , state:"IL" , city: "Hinsdale" , zip: 60521, rating: 4, password: "111111")
chicagoHospital11 = Clinic.create(name:"Amitall Health Adventist Medical Center Hinsdale", email: 'islammm@gmail.com', address:"120 N Oak St" , state:"IL" , city: "Hinsdale" , zip: 60521, rating: 4, password: "111111")
chicagoHospital12 = Clinic.create(name:"Amita;; Health Adventist Medical Center Hinsdale", email: 'islammmmm@gmail.com', address:"120 N Oak St" , state:"IL" , city: "Hinsdale" , zip: 60521, rating: 4, password: "111111")
chicagoHospital13 = Clinic.create(name:"Amitkkkk Health Adventist Medical Center Hinsdale", email: 'islammmmmm@gmail.com', address:"120 N Oak St" , state:"IL" , city: "Hinsdale" , zip: 60521, rating: 4, password: "111111")

clinicCreate = ClinicsInsurance.create(insurance_id: 1, clinic_id: 1)
clinicCreate = ClinicsInsurance.create(insurance_id: 2, clinic_id: 1)
clinicCreate = ClinicsInsurance.create(insurance_id: 1, clinic_id: 2)
clinicCreate = ClinicsInsurance.create(insurance_id: 2, clinic_id: 2)

user1 = User.create(first_name: "Islam", last_name: "Madkaur", date_of_birth: Date.new(1996, 01, 06), email: "islam@gmail.com", address: "123 Ave", city: "Chicago", state:"IL", zipcode:"60615", password:"111111")
doctor1 = Doctor.create(first_name: "Islam", last_name: "Madkaur", date_of_birth: Date.new(1996, 01, 06), email: "islam2@gmail.com", address: "123 Ave", password:"111111", gender: 'Male', specialty_id: 1)
doctor2 = Doctor.create(first_name: "Doctor", last_name: "Pepper", date_of_birth: Date.new(1996, 01, 06), email: "doc@gmail.com", address: "123 Ave", password:"111111", gender: 'Male', specialty_id: 2)
doctor3 = Doctor.create(first_name: "Pink", last_name: "Bubbles", date_of_birth: Date.new(1996, 01, 06), email: "pinky@gmail.com", address: "123 Ave", password:"111111", gender: 'Female', specialty_id: 5)


message1 = Message.create(message: 'Hello Doctor')
message1 = Message.create(message: 'Testing More Messages')

userDoctorMessage = UserDoctorMessage.create(user_id: 1, doctor_id: 1, message_id: 1)
userDoctorMessage2 = UserDoctorMessage.create(user_id: 1, doctor_id: 1, message_id: 2)

doctorSpecialty = DoctorSpecialty.create(specialty_id: 1, doctor_id: 1)

doctorHospital = DoctorHospital.create(clinic_id: 1, doctor_id: 1)
doctorHospital2 = DoctorHospital.create(clinic_id: 1, doctor_id: 2)
doctorHospital3 = DoctorHospital.create(clinic_id: 2, doctor_id: 1)



monday1 = Monday.create(available: true, start: 1, end: 2, doctor_id: 1)
monday2 = Monday.create(start: 8, end: 17, doctor_id: 2)

tuesday1 = Tuesday.create(available: true , start: 1, end: 2, doctor_id: 1)
tuesday2 = Tuesday.create(available: true , start: 8, end: 17, doctor_id: 2)

wednesday1 = Wednesday.create(available: true , start: 1, end: 2, doctor_id: 1)
wednesday2 = Wednesday.create(available: true , start: 8, end: 17, doctor_id: 2)

tuesday1 = Thursday.create(available: true , start: 1, end: 2, doctor_id: 1)
tuesday2 = Thursday.create(available: true , start: 8, end: 17, doctor_id: 2)

friday1 = Friday.create(available: true , start: 1, end: 2, doctor_id: 1)
friday2 = Friday.create(available: true , start: 8, end: 17, doctor_id: 2)

saturday1 = Saturday.create(available: true , start: 1, end: 2, doctor_id: 1)
saturday2 = Saturday.create(available: true , start: 8, end: 17, doctor_id: 2)

sunday1 = Sunday.create(available: true , start: 1, end: 2, doctor_id: 1)
sunday2 = Sunday.create(available: true , start: 8, end: 17, doctor_id: 2)

Appointment.create(booked: true, date: DateTime.new(2021, 03, 22), start: DateTime.new(2021, 03, 22, 12), end: DateTime.new(2021, 03, 22, 13), doctor_id: 1, user_id: 1, appointment_doctor_user_id: 1)
Appointment.create(booked: true, date: DateTime.new(2021, 03, 22), start: DateTime.new(2021, 03, 22, 12), end: DateTime.new(2021, 03, 22, 13), doctor_id: 1, user_id: 1, appointment_doctor_user_id: 2)

AppointmentDoctorUser.create(user_id: 1, doctor_id: 1, appointment_id: 1, monday_id: 1)
AppointmentDoctorUser.create(user_id: 1, doctor_id: 1, appointment_id: 2, tuesday_id: 1)







